-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


ALTER TABLE IF EXISTS public.team_to_player DROP CONSTRAINT IF EXISTS teams_player_id_fkey;

ALTER TABLE IF EXISTS public.team_to_player DROP CONSTRAINT IF EXISTS teams_teams_id_fkey;

ALTER TABLE IF EXISTS public.match DROP CONSTRAINT IF EXISTS team1;

ALTER TABLE IF EXISTS public.match DROP CONSTRAINT IF EXISTS team2;



DROP TABLE IF EXISTS public.admins;

CREATE TABLE IF NOT EXISTS public.admins
(
    user_id serial NOT NULL,
    username text COLLATE pg_catalog."default" NOT NULL,
    email text COLLATE pg_catalog."default" NOT NULL,
    password text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT admins_pkey PRIMARY KEY (user_id),
    CONSTRAINT admins_email_key UNIQUE (email),
    CONSTRAINT admins_username_key UNIQUE (username)
);

DROP TABLE IF EXISTS public.players;

CREATE TABLE IF NOT EXISTS public.players
(
    player_id serial NOT NULL,
    name text COLLATE pg_catalog."default",
    matches_played integer NOT NULL,
    runs integer NOT NULL,
    average real NOT NULL,
    strike_rate real NOT NULL,
    CONSTRAINT players_pkey PRIMARY KEY (player_id)
);

DROP TABLE IF EXISTS public.team_to_player;

CREATE TABLE IF NOT EXISTS public.team_to_player
(
    team_id serial NOT NULL,
    player_id integer NOT NULL,
    player_role text COLLATE pg_catalog."default",
    CONSTRAINT teams_pkey PRIMARY KEY (team_id, player_id)
);

DROP TABLE IF EXISTS public.teams;

CREATE TABLE IF NOT EXISTS public.teams
(
    team_id serial NOT NULL,
    name text COLLATE pg_catalog."default" NOT NULL,
    CONSTRAINT teams_pkey1 PRIMARY KEY (team_id),
    CONSTRAINT name UNIQUE (name)
);

DROP TABLE IF EXISTS public.match;

CREATE TABLE IF NOT EXISTS public.match
(
    match_id serial NOT NULL,
    team_1 text NOT NULL,
    team_2 text NOT NULL,
    date date,
    venue text,
    status text,
    PRIMARY KEY (match_id)
);

ALTER TABLE IF EXISTS public.team_to_player
    ADD CONSTRAINT teams_player_id_fkey FOREIGN KEY (player_id)
    REFERENCES public.players (player_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.team_to_player
    ADD CONSTRAINT teams_teams_id_fkey FOREIGN KEY (team_id)
    REFERENCES public.teams (team_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.match
    ADD CONSTRAINT team1 FOREIGN KEY (team_1)
    REFERENCES public.teams (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.match
    ADD CONSTRAINT team2 FOREIGN KEY (team_2)
    REFERENCES public.teams (name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;